# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2025 Mono Technologies Inc.

obj-y += i2c_helpers.o
obj-y += voltage_sensors.o
obj-y += usbpd_controller.o
obj-y += typec_controller.o
obj-y += rtc.o
obj-y += led_controller.o
obj-y += eeprom.o
obj-y += retimer.o
obj-y += clock_gen.o
obj-y += fan_controller.o
obj-y += temp_sensors.o